import classes from "./page.module.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en" className={classes.html}>
      <body className={classes.body}>{children}</body>
    </html>
  )
}
